<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{0950bf5e-e2f0-4469-b3ab-cc3e91081a00}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

	SysRun					: BYTE;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SysRun := SysRun + 1;

EventLoggerManager();

RETURN;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="15" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="63" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>